// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ciaPc9BX0cMFJgcTe9-nAqNu6_FA-xg',
    appId: '1:194092432593:web:470f522ba579c85d8dd9f0',
    messagingSenderId: '194092432593',
    projectId: 'dam-u4-autos-ittepic',
    authDomain: 'dam-u4-autos-ittepic.firebaseapp.com',
    storageBucket: 'dam-u4-autos-ittepic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFyf_jcAq9YoZ8SEIJ4NOpqepe5ZdnZVM',
    appId: '1:194092432593:android:aeb98a55a377c9438dd9f0',
    messagingSenderId: '194092432593',
    projectId: 'dam-u4-autos-ittepic',
    storageBucket: 'dam-u4-autos-ittepic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1agtQIBWqnyUoiXxTXQt9OOipCAudWXE',
    appId: '1:194092432593:ios:7221d128d3cf96048dd9f0',
    messagingSenderId: '194092432593',
    projectId: 'dam-u4-autos-ittepic',
    storageBucket: 'dam-u4-autos-ittepic.appspot.com',
    iosClientId: '194092432593-qhgrqar3b8arepflim37pc08nj9t5tdm.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto1',
  );
}
